volumes:
  keycloak-db-data:
    driver: local

services:
  postgres:
    image: postgres:13.7
    container_name: postgres_keycloak_c
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
  keycloak:
    build: .
    container_name: custom-auth-service
    environment:
      #Admin Credentials
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=My863Keycloak
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=My863Keycloak
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_SPI_THEME_DEFAULT=theme1
    command: ["start-dev"]
    
    ports:
      - 18443:8443
      - 18081:8080
    depends_on:
      - postgres